In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
df=pd.read_csv('/kaggle/input/playground-series-s4e7/train.csv')
df.head()

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s4e7/sample_submission.csv
/kaggle/input/playground-series-s4e7/train.csv
/kaggle/input/playground-series-s4e7/test.csv


id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0   0    Male   21                1         35.0                   0   
1   1    Male   43                1         28.0                   0   
2   2  Female   25                1         14.0                   1   
3   3  Female   35                1          1.0                   0   
4   4  Female   36                1         15.0                   1   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    1-2 Year            Yes         65101.0                 124.0      187   
1   > 2 Years            Yes         58911.0                  26.0      288   
2    < 1 Year             No         38043.0                 152.0      254   
3    1-2 Year            Yes          2630.0                 156.0       76   
4    1-2 Year             No         31951.0                 152.0      294   

   Response  
0         0  
1         1  
2         0  
3         0  
4         0

In [2]:
df.shape

(11504798, 12)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11504798 entries, 0 to 11504797
Data columns (total 12 columns):
 #   Column                Dtype  
---  ------                -----  
 0   id                    int64  
 1   Gender                object 
 2   Age                   int64  
 3   Driving_License       int64  
 4   Region_Code           float64
 5   Previously_Insured    int64  
 6   Vehicle_Age           object 
 7   Vehicle_Damage        object 
 8   Annual_Premium        float64
 9   Policy_Sales_Channel  float64
 10  Vintage               int64  
 11  Response              int64  
dtypes: float64(3), int64(6), object(3)
memory usage: 1.0+ GB


In [4]:
df.describe()

id           Age  Driving_License   Region_Code  \
count  1.150480e+07  1.150480e+07     1.150480e+07  1.150480e+07   
mean   5.752398e+06  3.838356e+01     9.980220e-01  2.641869e+01   
std    3.321149e+06  1.499346e+01     4.443120e-02  1.299159e+01   
min    0.000000e+00  2.000000e+01     0.000000e+00  0.000000e+00   
25%    2.876199e+06  2.400000e+01     1.000000e+00  1.500000e+01   
50%    5.752398e+06  3.600000e+01     1.000000e+00  2.800000e+01   
75%    8.628598e+06  4.900000e+01     1.000000e+00  3.500000e+01   
max    1.150480e+07  8.500000e+01     1.000000e+00  5.200000e+01   

       Previously_Insured  Annual_Premium  Policy_Sales_Channel       Vintage  \
count        1.150480e+07    1.150480e+07          1.150480e+07  1.150480e+07   
mean         4.629966e-01    3.046137e+04          1.124254e+02  1.638977e+02   
std          4.986289e-01    1.645475e+04          5.403571e+01  7.997953e+01   
min          0.000000e+00    2.630000e+03          1.000000e+00  1.000000e+01   
25%          0.000000e+00    2.527700e+04          2.900000e+01  9.900000e+01   
50%          0.000000e+00    3.182400e+04          1.510000e+02  1.660000e+02   
75%          1.000000e+00    3.945100e+04          1.520000e+02  2.320000e+02   
max          1.000000e+00    5.401650e+05          1.630000e+02  2.990000e+02   

           Response  
count  1.150480e+07  
mean   1.229973e-01  
std    3.284341e-01  
min    0.000000e+00  
25%    0.000000e+00  
50%    0.000000e+00  
75%    0.000000e+00  
max    1.000000e+00

In [5]:
df.isnull().sum()

id                      0
Gender                  0
Age                     0
Driving_License         0
Region_Code             0
Previously_Insured      0
Vehicle_Age             0
Vehicle_Damage          0
Annual_Premium          0
Policy_Sales_Channel    0
Vintage                 0
Response                0
dtype: int64

In [6]:
df.nunique()

id                      11504798
Gender                         2
Age                           66
Driving_License                2
Region_Code                   54
Previously_Insured             2
Vehicle_Age                    3
Vehicle_Damage                 2
Annual_Premium             51728
Policy_Sales_Channel         152
Vintage                      290
Response                       2
dtype: int64

In [7]:
df.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0   0    Male   21                1         35.0                   0   
1   1    Male   43                1         28.0                   0   
2   2  Female   25                1         14.0                   1   
3   3  Female   35                1          1.0                   0   
4   4  Female   36                1         15.0                   1   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    1-2 Year            Yes         65101.0                 124.0      187   
1   > 2 Years            Yes         58911.0                  26.0      288   
2    < 1 Year             No         38043.0                 152.0      254   
3    1-2 Year            Yes          2630.0                 156.0       76   
4    1-2 Year             No         31951.0                 152.0      294   

   Response  
0         0  
1         1  
2         0  
3         0  
4         0

In [8]:
x = df.drop(columns=['id', 'Response'])
y = df['Response']

In [9]:
x_encoded = pd.get_dummies(x, columns=['Gender', 'Vehicle_Age', 'Vehicle_Damage'])

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x_encoded, y, test_size=0.2, random_state=42)

In [11]:
dt = DecisionTreeClassifier(random_state=42)

In [12]:
dt.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [13]:
y_pred_dt = dt.predict(x_test)

In [14]:
accuracy_dt = accuracy_score(y_test, y_pred_dt)
report_dt = classification_report(y_test, y_pred_dt)
conf_matrix_dt = confusion_matrix(y_test, y_pred_dt)

print("Decision Tree Classifier")
print(f"Accuracy: {accuracy_dt}")
print("Classification Report:")
print(report_dt)
print("Confusion Matrix:")
print(conf_matrix_dt)

Decision Tree Classifier
Accuracy: 0.8324416765176275
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.90      0.90   2017776
           1       0.33      0.34      0.33    283184

    accuracy                           0.83   2300960
   macro avg       0.62      0.62      0.62   2300960
weighted avg       0.84      0.83      0.83   2300960

Confusion Matrix:
[[1818407  199369]
 [ 186176   97008]]


In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier

In [16]:
lr = LogisticRegression(random_state=42, max_iter=1000)

lr.fit(x_train, y_train)

y_pred_lr = lr.predict(x_test)

accuracy_lr = accuracy_score(y_test, y_pred_lr)
report_lr = classification_report(y_test, y_pred_lr)
conf_matrix_lr = confusion_matrix(y_test, y_pred_lr)

print("Logistic Regression Classifier")
print(f"Accuracy: {accuracy_lr}")
print("Classification Report:")
print(report_lr)
print("Confusion Matrix:")
print(conf_matrix_lr)

/usr/local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic Regression Classifier
Accuracy: 0.876837928516793
Classification Report:
              precision    recall  f1-score   support

           0       0.88      1.00      0.93   2017776
           1       0.21      0.00      0.00    283184

    accuracy                           0.88   2300960
   macro avg       0.55      0.50      0.47   2300960
weighted avg       0.80      0.88      0.82   2300960

Confusion Matrix:
[[2017492     284]
 [ 283107      77]]


In [17]:
adb = AdaBoostClassifier(n_estimators=100, random_state=42)

adb.fit(x_train, y_train)

y_pred_adb = adb.predict(x_test)


accuracy_adb = accuracy_score(y_test, y_pred_adb)
report_adb = classification_report(y_test, y_pred_adb)
conf_matrix_adb = confusion_matrix(y_test, y_pred_adb)

print("\nAdaBoost Classifier")
print(f"Accuracy: {accuracy_adb}")
print("Classification Report:")
print(report_adb)
print("Confusion Matrix:")
print(conf_matrix_adb)

/usr/local/lib/python3.10/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(



AdaBoost Classifier
Accuracy: 0.876899641888603
Classification Report:
              precision    recall  f1-score   support

           0       0.88      1.00      0.93   2017776
           1       0.49      0.00      0.01    283184

    accuracy                           0.88   2300960
   macro avg       0.68      0.50      0.47   2300960
weighted avg       0.83      0.88      0.82   2300960

Confusion Matrix:
[[2016467    1309]
 [ 281940    1244]]
